version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: Migrationmaster0
      ACCEPT_EULA: "Y"
  migrated-db:
    container_name: migrated-db-postgres
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'